version: '3'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.4
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./schema_design/db_schema.sql:/docker-entrypoint-initdb.d/db_schema.sql
    env_file:
      - ./sqlite_to_postgres/.env



  web:
    build: .
    restart: always
    command: bash -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn config.wsgi:application --preload --bind 0.0.0.0:8000"
    depends_on:
      - db
    env_file:
      - ./movies_admin/.env.sample
    volumes:
      - static_volume:/code/static/
    expose:
      - 8000


  nginx:
    image: nginx:1.19.2
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site-enable/:/etc/nginx/site-enable/site.conf:ro
      - static_volume:/code/static/

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
    container_name: es01
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elasticdb:/usr/share/elasticsearch/data
